### ISSUE TITLE
I can not open the file NVSP1.SGY.

### ISSUE THREAD

**Issue by feliperails** [equinor/segyio#365]
I can not open the file NVSP1.SGY.
```
Traceback (most recent call last):
  File "console.py", line 24, in <module>
    segyio.open("/mnt/d/segy/NVSP1.SGY", "r")
  File "/home/felipe/anaconda3/lib/python3.6/site-packages/segyio/open.py", line 187, in open
    return infer_geometry(f, metrics, iline, xline, strict)
  File "/home/felipe/anaconda3/lib/python3.6/site-packages/segyio/open.py", line 7, in infer_geometry
    cube_metrics = f.xfd.cube_metrics(iline, xline)
RuntimeError: unable to find sorting.
```

This file is public and can be downloaded at https://wiki.seg.org/wiki/Stratton_3D_survey.

Could you help me understand why it's not working?
I tried Windows 10 and Ubuntu and the exact same error occurs.

**Comment by jokva** [comment]
Most likely it's not a proper revision 1 volume. A quick glance at the headers confirms this.

```
>>> f = segyio.open('NVSP1.SGY', ignore_geometry=True)
>>> f.attributes(189)[:]
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int32)
>>> f.attributes(193)[:]
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int32)

```

**Comment by jokva** [comment]
The file itself opens and looks perfectly fine.

**Comment by jokva** [comment]
The file looks fine, so I'll consider this a solved issue now. If you run into more problems, please re-open or create a new issue.
