### ISSUE TITLE
Invalid code in setup.py: cmdclass = { 'test': setuptools.command.test.test },

### ISSUE THREAD

**Issue by yurivict** [equinor/segyio#586]
[This](https://github.com/equinor/segyio/blob/master/python/setup.py#L98) line references ```setuptools.command.test.test``` that doesn't exist in ```setuptools-63.1.0```:

```
===>  Configuring for py311-segyio-1.9.12
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 98, in <module>
    cmdclass = { 'test': setuptools.command.test.test },
                         ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'setuptools.command' has no attribute 'test'
*** Error code 1
```

Python-3.11
FreeBSD 14.1

**Comment by ajaust** [comment]
Thanks for the report! I think this should be fixed if https://github.com/equinor/segyio/pull/576/ gets merged.

**Comment by ajaust** [comment]
#576 was merged so it should work now. 🙂
